ALTER TABLE address RENAME COLUMN state TO uf;

ALTER TABLE address
  ALTER COLUMN cep TYPE VARCHAR(9),
  ALTER COLUMN cep SET NOT NULL,
  ALTER COLUMN street SET NOT NULL,
  ALTER COLUMN number TYPE VARCHAR(16),
  ALTER COLUMN neighborhood TYPE VARCHAR(128),
  ALTER COLUMN neighborhood SET NOT NULL,
  ALTER COLUMN city TYPE VARCHAR(128),
  ALTER COLUMN city SET NOT NULL,
  ALTER COLUMN uf TYPE VARCHAR(2),
  ALTER COLUMN uf SET NOT NULL;
